services:
  prometheus:
    build: ./prometheus       # 👈 그라파나처럼 직접 굽기로 통일!
    container_name: prometheus
    ports:
      - "9090:9090"
    extra_hosts:              # 👈 로컬 호스트(스프링 부트)와 통신하기 위한 뚫기
      - "host.docker.internal:host-gateway"

  grafana:
    build: ./grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_DISABLE_LOGIN_FORM=true    # 별도 로그인 없이 대시보드 조회
