dependencies {
    api project(':token-pilot-core')
    api 'io.micrometer:micrometer-core:1.17.0'
    compileOnly project(':token-pilot-budget')
    compileOnly project(':token-pilot-notification')

    testImplementation project(':token-pilot-budget')
    testImplementation project(':token-pilot-notification')
}
